version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - default

  # mysql:
  #   container_name: mysql_db
  #   image: mysql:8.0
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_DATABASE: products
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: '123'
  #     MYSQL_ROOT_PASSWORD: 'admin' 
  #   networks:
  #     - default

  postgres:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      - default

  redis:
    container_name: redis
    image: redis
    restart: always
    networks:
      - default

  elasticsearch:
    container_name: elasticsearch_db
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - default

networks:
  default:
    driver: bridge